export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_POSTS_BY_USER = "GET_ALL_POSTS_BY_USER";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const SEARCH = "SEARCH";
export const SORT = "SORT";

//Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//create Transactions

export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ALL_TRANSACTIONS_SUCCESS = "GET_ALL_TRANSACTIONS_SUCCESS";
export const GET_ALL_TRANSACTIONS_FAILURE = "GET_ALL_TRANSACTIONS_FAILURE";

export const ADD_MONEY = "ADD_MONEY";
export const ADD_MONEY_SUCCESS = "ADD_MONEY_SUCCESS";
export const ADD_MONEY_FAILURE = "ADD_MONEY_FAILURE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
